spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TecHelp;encrypt=true;trustServerCertificate=true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  jackson:
    time-zone: America/Sao_Paulo
    date-format: dd/MM/yyyy
server:
  servlet:
    context-path: /techelp/api
logging:
  level:
    br.com.TecHelpAPI: INFO
    root: WARN
